const routes = {
  HomePage: '/',
  TypographyPage: '/typography',
  ButtonPage: '/buttons',
  CheckmarksPage: '/checkmarks',
  RadioButtonsPage: '/radios',
  TextFieldPage: '/textfield',
  SelectPage: '/select',
  SwitchPage: '/switch',
  RatingPage: '/rating',
  AutoCompletePage: 'autoComplete',
  BoxPage: '/box',
  CardPage: '/card',
  AccordionPage: '/accordion',
  ImagesPage: '/images',
  AvatarPage: '/avatar',
  BottomNavPage: '/bottomNav',
  DrawerPage: '/drawer',
  BreadCrumbsPage: '/breadcrumbs',
  SpeedDialPage: '/speedDial',
  LinksPage: '/links',
  NavBarPage: '/navbar',
  BadgePage: '/badge',
  ChipPage: '/chip',
  ListPage: '/list',
  AlertPage: '/alert',
  CutsomThemePage: '/customtheme',
  DateRangePickerPage: '/dateRangePicker',
  DateTimePickerPage: '/dateTimePicker',
  DialogPage: '/dialog',
  LayoutPage: '/layout',
  LoudingButtonPage: '/loudingButton',
  MasonryPage: '/masonry',
  ProgressPage: '/progress',
  SkeletonPage: '/skeleton',
  SnackBarPage: '/snackBar',
  TabPage: '/tab',
  TimlinePage: '/timline',
  ToolTipsPage: '/toolTips',
  TablePage: '/table',

} as const;

export type Routes = typeof routes;
export type RouteLink = Routes[keyof Routes];

export default routes;
